<a href="https://colab.research.google.com/github/Nitin-Flavier13/Pytorch-For-DeepLearning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello nitin")

hello nitin


In [15]:
!nvidia-smi

Sun Feb 16 05:50:48 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   75C    P0             32W /   70W |     120MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu124


### Introduction to Tensors

torch.Tensor(): is a class in PyTorch that represents a multi-dimensional array (tensor). It is the core data structure in PyTorch, similar to NumPy arrays but with additional support for GPU acceleration and automatic differentiation.

- Key Features:
  - Multi-Dimensional: Supports scalars, vectors, matrices, and high-dimensional tensors.
  - Device Support: Can be moved between CPU and GPU (.to(device)).
  - Automatic Differentiation: Works with torch.autograd for gradient computation.
  - Efficient Computation: Optimized for deep learning operations.

In [ ]:
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [ ]:
print(scalar.ndim)
print(scalar.item())

0
7


In [ ]:
vector = torch.tensor([7,10])
print(vector.ndim)
print(vector.shape[0])

1
2


In [ ]:
matrix = torch.tensor([[2,3],[4,5]])
print(matrix.ndim)
print(matrix.shape)

2
torch.Size([2, 2])


In [ ]:
Tensor = torch.tensor([[[1,2,3],[3,4,5]],
                       [[10,11,12],[5,6,7]]])
print(Tensor.ndim)
print(Tensor.shape)
print(Tensor)

3
torch.Size([2, 2, 3])
tensor([[[ 1,  2,  3],
         [ 3,  4,  5]],

        [[10, 11, 12],
         [ 5,  6,  7]]])


### Random Tensors

Why do we need it ?

Neural Networks start with tensors full of random numbers & then adjust those random numbers to better represent the data.

In [ ]:
rand_tensor = torch.rand(4,5)
print(rand_tensor)
print(rand_tensor.ndim)
print(rand_tensor.shape)

tensor([[0.8707, 0.7474, 0.6519, 0.4923, 0.1198],
        [0.1484, 0.3140, 0.1829, 0.4489, 0.5615],
        [0.7288, 0.5688, 0.7359, 0.0583, 0.7737],
        [0.7057, 0.9049, 0.9281, 0.2090, 0.3340]])
2
torch.Size([4, 5])


In [ ]:
random_image_tensor = torch.rand(size=(224,224,3))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
# zeros & 1
zeros = torch.zeros(size=(5,4))
print(zeros)
ones = torch.ones(size=(5,4))
print(ones)
result = torch.matmul(rand_tensor,zeros)
print(result)
result = torch.matmul(rand_tensor,ones)
print(result)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[2.8821, 2.8821, 2.8821, 2.8821],
        [1.6558, 1.6558, 1.6558, 1.6558],
        [2.8654, 2.8654, 2.8654, 2.8654],
        [3.0817, 3.0817, 3.0817, 3.0817]])


In [ ]:
print(ones.dtype)
print(zeros.dtype)

torch.float32
torch.float32


In [ ]:
data = torch.arange(1,11)
data2 = torch.zeros_like(input=data)
print(data)
print(data2)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


### Tensor datatypes

Most common problems:
- Tensors not right datatype
- Tensors not right shape
- Tensors not on the right device

In [ ]:
float_32_tensor = torch.tensor([3,4.0,5.0],
                               dtype=None
                               ,device=None # what device is the tensor on ?
                               ,requires_grad=False) # wether or not to Track Gradient with this Tensor operation.
print(float_32_tensor)

tensor([3., 4., 5.])


In [ ]:
# converting float_32 tensor to float_16
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

ans = float_16_tensor * float_32_tensor
print("float16 * float32 = ",ans.dtype)

int32 = torch.tensor([1,2,3],dtype=torch.int32)
ans2 = int32*float_32_tensor
print("int32 * float32 = ",ans2.dtype)

ans3 = int32*float_16_tensor
print("int32 * float16 = ",ans3.dtype)


float16 * float32 =  torch.float32
int32 * float32 =  torch.float32
int32 * float16 =  torch.float16


In [ ]:
print(float_16_tensor.device)
print(float_16_tensor.size())
print(float_16_tensor.shape)

cpu
torch.Size([3])
torch.Size([3])


In [ ]:
# Manipulating Tensors
tensor = torch.tensor([1,2,3,4])
print(tensor + 10)
print(tensor*10) # element wise multiplication
print(torch.mul(tensor,5))

tensor([11, 12, 13, 14])
tensor([10, 20, 30, 40])
tensor([ 5, 10, 15, 20])


torch.matmul() -> does dot product if both inputs are 1d tensors

In [ ]:
# matrix multiplication (dot product)
print(tensor)
print(tensor.shape)
print(torch.matmul(tensor,tensor))

print(tensor.view(-1,1))
print(tensor.view(-1,1).shape)
tensor2 = tensor.view(-1,1)
print(torch.matmul(tensor,tensor2))

tensor([1, 2, 3, 4])
torch.Size([4])
tensor(30)
tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([4, 1])
tensor([30])


In [ ]:
data = torch.rand(1000)

In [ ]:
%%time
ans = 0
for i in range(1000):
  ans += data[i]*data[i]
print(ans)

tensor(337.6126)
CPU times: user 13.7 ms, sys: 959 µs, total: 14.7 ms
Wall time: 16.3 ms


In [ ]:
%%time
ans = torch.matmul(data,data).item()
print(ans)

337.61260986328125
CPU times: user 914 µs, sys: 0 ns, total: 914 µs
Wall time: 661 µs


In [ ]:
tensor @ tensor  # leads to matmul

tensor(30)

In [ ]:
tensor_a = tensor.view(-1,1)
tensor_b = tensor.T
print(tensor," ",tensor.shape)
print(tensor_a," ",tensor_a.shape)
print(tensor_b," ",tensor_b.shape)

tensor([1, 2, 3, 4])   torch.Size([4])
tensor([[1],
        [2],
        [3],
        [4]])   torch.Size([4, 1])
tensor([1, 2, 3, 4])   torch.Size([4])


In [ ]:
tensor_a = torch.rand(3,2)
tensor_b = torch.rand(2,3)

torch.mm(tensor_a,tensor_b)

tensor([[0.2012, 0.7115, 1.2932],
        [0.3127, 0.3958, 1.0875],
        [0.1476, 0.1550, 0.4720]])

### Finding min, max, mean, sum

In [ ]:
x = torch.rand(200)
print(x.min())
print(x.max())
print(x.mean())  # mean() works on floating tensors
print(type(x.sum().item()))

tensor(0.0039)
tensor(0.9945)
tensor(0.4949)
<class 'float'>


In [ ]:
print(x.argmin())
print(x.argmax())

tensor(96)
tensor(197)


### Reshaping, stacking, squeezing, unsqueezing

* Reshaping: reshape input tensor to defined shape.
* View: return a view of an input tensor of certain shape, keeping the same memory.
* stack: horizontal or vertical addition of tensors.
* squeezing: removes '1' dimension from tensor.
* unsqueeze: adds 1 dimension to the target tensor.
* permute: return a view of the input with dimensions swapped in certain way.

* Reshape:
  - Flexibility: reshape can return a tensor with a different shape than the original tensor, and it can do so in a more flexible way. It internally checks if it can return a new tensor with the requested shape, either by sharing memory with the original tensor or by making a new copy, depending on the situation.
  - Memory Handling: It may return a new tensor if necessary, which might not share the same underlying memory as the original tensor.

In [ ]:
import torch

x = torch.arange(1,10)
x_ch = x.reshape(3,3)
print(x_ch,x_ch.shape)
x_ch = x.reshape(9,1)
print(x_ch,x_ch.shape)
x_ch = x.reshape(1,9)
print(x_ch,x_ch.shape)

x_ch[0][4] = -100
print(x_ch,x_ch.shape)
print(x,x.shape)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) torch.Size([3, 3])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]) torch.Size([9, 1])
tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]) torch.Size([1, 9])
tensor([[   1,    2,    3,    4, -100,    6,    7,    8,    9]]) torch.Size([1, 9])
tensor([   1,    2,    3,    4, -100,    6,    7,    8,    9]) torch.Size([9])


* View:
  - Memory Contiguity: view requires the tensor to be contiguous in memory. If the tensor is not contiguous (i.e., the elements are not stored in a single continuous block of memory), then calling view will throw an error. The result of view will always be a new tensor that shares the same memory as the original tensor (it doesn't copy the data unless necessary).
  - Faster and Memory-Efficient: Since view operates directly on the existing memory, it can be faster and more memory-efficient when the tensor is contiguous.

In [ ]:
# view
# z shares the same memory with x, so changing z will also change x

z = x.view(9,1)
z[3] = 100
print(z,z.shape)
print(x,x.shape)


tensor([[   1],
        [   2],
        [   3],
        [ 100],
        [-100],
        [   6],
        [   7],
        [   8],
        [   9]]) torch.Size([9, 1])
tensor([   1,    2,    3,  100, -100,    6,    7,    8,    9]) torch.Size([9])


In [ ]:
# stack tensors

x_stacked = torch.stack([x,x,x],dim=0)
print(x_stacked,x_stacked.shape)
x_stacked = torch.stack([x,x,x],dim=1)
print(x_stacked,x_stacked.shape,end="\n\n\n")

print("Lets see stacking at different dimensions")
print(x_stacked,x_stacked.shape,end="\n\n")
x_stacked = torch.stack([x_ch,x_ch,x_ch],dim=0)
print(x_stacked,x_stacked.shape,end="\n\n")
x_stacked = torch.stack([x_ch,x_ch,x_ch],dim=1)
print(x_stacked,x_stacked.shape,end="\n\n")
x_stacked = torch.stack([x_ch,x_ch,x_ch],dim=2)
print(x_stacked,x_stacked.shape)

tensor([[   1,    2,    3,  100, -100,    6,    7,    8,    9],
        [   1,    2,    3,  100, -100,    6,    7,    8,    9],
        [   1,    2,    3,  100, -100,    6,    7,    8,    9]]) torch.Size([3, 9])
tensor([[   1,    1,    1],
        [   2,    2,    2],
        [   3,    3,    3],
        [ 100,  100,  100],
        [-100, -100, -100],
        [   6,    6,    6],
        [   7,    7,    7],
        [   8,    8,    8],
        [   9,    9,    9]]) torch.Size([9, 3])


Lets see stacking at different dimensions
tensor([[   1,    1,    1],
        [   2,    2,    2],
        [   3,    3,    3],
        [ 100,  100,  100],
        [-100, -100, -100],
        [   6,    6,    6],
        [   7,    7,    7],
        [   8,    8,    8],
        [   9,    9,    9]]) torch.Size([9, 3])

tensor([[[   1,    2,    3,  100, -100,    6,    7,    8,    9]],

        [[   1,    2,    3,  100, -100,    6,    7,    8,    9]],

        [[   1,    2,    3,  100, -100,    6,    7,    8,    9]]]

In [ ]:
# Squeeze Removes Dimensions having 1
x = torch.zeros(2, 1, 2, 1, 2)
print(x.size())
y = torch.squeeze(x)
print(y.size())
y = torch.squeeze(x, 0)
print(y.size())
y = torch.squeeze(x, 1)
print(y.size())
y = torch.squeeze(x, (1, 2, 3))

torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 2])
torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 1, 2])


In [ ]:
# unsqueeze adds single dimension to a tensor at the specified dimension
x = torch.rand(3,4)
print(x,x.shape)
x_un = x.unsqueeze(dim=0)
print("At 0th dimension:\n",x_un,x_un.shape)
x_un = x.unsqueeze(dim=1)
print("At 1st dimension:\n",x_un,x_un.shape)
x_un = x.unsqueeze(dim=2)
print("At 2nd dimension:\n",x_un,x_un.shape)

tensor([[0.3943, 0.0036, 0.5839, 0.9437],
        [0.4151, 0.2282, 0.8094, 0.4524],
        [0.8734, 0.5335, 0.1846, 0.2489]]) torch.Size([3, 4])
At 0th dimension:
 tensor([[[0.3943, 0.0036, 0.5839, 0.9437],
         [0.4151, 0.2282, 0.8094, 0.4524],
         [0.8734, 0.5335, 0.1846, 0.2489]]]) torch.Size([1, 3, 4])
At 1st dimension:
 tensor([[[0.3943, 0.0036, 0.5839, 0.9437]],

        [[0.4151, 0.2282, 0.8094, 0.4524]],

        [[0.8734, 0.5335, 0.1846, 0.2489]]]) torch.Size([3, 1, 4])
At 2nd dimension:
 tensor([[[0.3943],
         [0.0036],
         [0.5839],
         [0.9437]],

        [[0.4151],
         [0.2282],
         [0.8094],
         [0.4524]],

        [[0.8734],
         [0.5335],
         [0.1846],
         [0.2489]]]) torch.Size([3, 4, 1])


In [ ]:
### permute returns a view of original tensor input with its dimensions permuted, and it has the same memory as the original one

x = torch.rand(3,2,4)
print(x,x.shape)

x_per = x.permute(2,0,1)
print(x_per,x_per.shape)

tensor([[[0.6491, 0.8718, 0.4111, 0.4785],
         [0.2471, 0.8033, 0.4063, 0.9766]],

        [[0.1779, 0.4481, 0.2360, 0.7486],
         [0.4610, 0.1333, 0.8256, 0.8975]],

        [[0.0066, 0.6208, 0.5278, 0.6103],
         [0.8165, 0.7105, 0.9476, 0.9040]]]) torch.Size([3, 2, 4])
tensor([[[0.6491, 0.2471],
         [0.1779, 0.4610],
         [0.0066, 0.8165]],

        [[0.8718, 0.8033],
         [0.4481, 0.1333],
         [0.6208, 0.7105]],

        [[0.4111, 0.4063],
         [0.2360, 0.8256],
         [0.5278, 0.9476]],

        [[0.4785, 0.9766],
         [0.7486, 0.8975],
         [0.6103, 0.9040]]]) torch.Size([4, 3, 2])


In [ ]:
t = torch.tensor([[
    [[1],[2],[3]],
    [[6],[5],[4]],
    [[7],[8],[9]]]
])
print(t[0][0][1][0].item())
print(t[0][0][1].item())
print(t[0][0])
t.shape

2
2
tensor([[1],
        [2],
        [3]])


torch.Size([1, 3, 3, 1])

In [ ]:
# i want 2,5,8
print(t[:,:,1,0])
print(t[:,:,1,0][0])
print(t[:,:,1,0][0][0])
print(t[0][1][2][0])

tensor([[2, 5, 8]])
tensor([2, 5, 8])
tensor(2)
tensor(4)


### Numpy & Pytorch

In [ ]:
import torch
import numpy as np

arr = np.arange(1.0,8.0)
t1 = torch.from_numpy(arr)
t2 = torch.from_numpy(arr).type(torch.float32)
print(arr,arr.dtype)
print(t1,t1.dtype)
print(t2,t2.dtype)

[1. 2. 3. 4. 5. 6. 7.] float64
tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64) torch.float64
tensor([1., 2., 3., 4., 5., 6., 7.]) torch.float32


A thing to note is when we convert numpy to tensor, its datatype is not default torch.float32

In [ ]:
arr = arr + 1
print(arr)
print(t1)
print(t2)

[2. 3. 4. 5. 6. 7. 8.]
tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)
tensor([1., 2., 3., 4., 5., 6., 7.])


In [ ]:
# tensor to numpy
t3 = torch.ones(7)
arr2 = t3.numpy()

print(t3,t3.dtype)
print(arr2,arr2.dtype)

tensor([1., 1., 1., 1., 1., 1., 1.]) torch.float32
[1. 1. 1. 1. 1. 1. 1.] float32


In [ ]:
# Reproduciblity (trying to take random out of random)

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
T1 = torch.rand(3,3)

torch.manual_seed(RANDOM_SEED)
T2 = torch.rand(3,3)
print(T1)
print(T1 == T2)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [1]:
import torch
torch.cuda.is_available()

True

In [12]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [3]:
# count the number of devices
torch.cuda.device_count()

1

### Putting tensors and models on GPU

In [5]:
t1 = torch.rand(1000)
print(t1[0:10],t1.device)

tensor([0.1285, 0.6139, 0.9162, 0.8551, 0.8385, 0.8038, 0.4520, 0.8014, 0.1447,
        0.1492]) cpu


In [13]:
# Move tensor to GPU if available
tensor_on_gpu = t1.to(device)
tensor_on_gpu[0:10]

tensor([0.1285, 0.6139, 0.9162, 0.8551, 0.8385, 0.8038, 0.4520, 0.8014, 0.1447,
        0.1492], device='cuda:0')

In [16]:
# move tensor back to cpu
# if tenor on GPU, we can't transform it to numpy
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu[0:10]

array([0.12852055, 0.61386144, 0.91624135, 0.85511625, 0.8385438 ,
       0.8038415 , 0.45200485, 0.80137247, 0.1447444 , 0.14917874],
      dtype=float32)